### PR TITLE
Test Single Nodes and Their Functions

### LINKED ISSUE #58: Test single nodes and their functions (when they are launched they remain up)

### PR DESCRIPTION
**Pull request by Yusuf-Serdar**
Closes #58 

This is a really big pull request, and I may have added some unnecessary tests. So I'd be grateful if you could take a look and let me know.

For the test_communication.py, I didn't add tests for can callback and ros listener callback because I assumed that can communication was covered in #55 . However, I can add them if necessary.

### CODE REVIEW

**Review by luca-byte — COMMENTED** [review]
Great job 💯 !!

I have yet to look at your PR, however some comments onn top of my head: I noticed that you are both using the single node `Agevar()`, and the node in the launch file, but this requires using the pytest mark and this collapses all tests together, making it more difficult to understand what happens in case of failures.

Given this aspect I would split the tests in two (which also make sense theoretically): one (or more) system test which verifies nodes and parameters (using launch_test) and different unit tests which launch the node programmatically and which are correcly identified by pytest. 

As for the tests, they seem reasonable, at the first sight. I will investigate into it further.

As for the communication node you should skip the tests if the cansocket is not available (check it with ip link as did Yunus in their PR, it is not necessary to set it up, but just checking it)

**Comment by Yusuf-Serdar** [comment]
GH Actions checks fail with ModuleNotFoundError, even though psutil has been added to the test dependencies in `package.xml` and `setup.py`. Not sure why it still fails. Any suggestions?

**Comment by luca-byte** [comment]
From what I know you should  not modify `setup.py` but only the `package.xml`. It  is not working because you specified the  wrong key. It is `python3-psutil` So: 
```xml
<test_depend>python3-psutil</test_depend>
```

**Review by luca-byte — COMMENTED** [review]
Great job 💯 

I noticed that the launch_tests that you have written share a lot of code, isn't there a way to create some class/functions that you can call to reduce the duplicated code? 

About the rest, the tests seem fine, I would just clarify in the Outline documentation which aspects are tested (which edge cases, the approach for the oracle, ...) very concisely, so that they can be easily looked up if needed.

**Review by luca-byte — APPROVED** [review]
LGTM!!! 🎯

GREAT job 💯 and also great commitment, given the short period of time you took for a task which was actually pretty big,

I will wait @lorixhack, just to be sure that I am not missing something.

**Review by luca-byte — APPROVED** [review]
LGTM

**Pull request merged**
